force-app/main/default/objects/Dispatch_Order__c/Dispatch_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Despacho</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Despacho</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Ordenes de Despacho</relationshipLabel>
    <relationshipName>Dispatch_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de despacho</fullName>
            </value>
            <value>
                <fullName>Despachada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/Dispatch_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Despacho</label>
    <nameField>
        <displayFormat>LOD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Despacho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Dispatch_Order__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Order__c</fullName>
    <label>Orden de Despacho</label>
    <referenceTo>Dispatch_Order__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Despacho</relationshipLabel>
    <relationshipName>Dispatch_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Linea de Orden de Compra</label>
    <referenceTo>Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Despacho</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Purchase_Orders_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Dispatch_Status__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Status__c</fullName>
    <label>Estado de Despacho</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Parcialmente</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Compra</label>
    <nameField>
        <displayFormat>LOC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Lineas de Ordern de Compra</relationshipLabel>
    <relationshipName>Purchas_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Quote_Line__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe estar relacionado a la cuenta seleccionada.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDispatchOrder.cls
@IsTest
public class TestDispatchOrder {
    @IsTest
    static void createDispatchOrder(){
        Quote__c quote = TestSetup.createQuote();
        String purchaseOrderId = ClassPurchaseOrder.createPurchaseOrder(quote.Id, quote.Contact__c, null);
        List<Purchase_Order_Line__c> purchaseOrderLines = [SELECT Id FROM Purchase_Order_Line__c WHERE Purchase_Order__c =: purchaseOrderId];

        Dispatch_Order_Line__c dispatchOrderLine;
        List<Dispatch_Order_Line__c> dispatchOrderLines = new List<Dispatch_Order_Line__c>();
        for (Integer i = 0; i < purchaseOrderLines.size(); i++){
            dispatchOrderLine =  new Dispatch_Order_Line__c();
            dispatchOrderLine.Purchase_Order_Line__c = purchaseOrderLines[i].Id;
            dispatchOrderLine.Quantity__c = 5 + i;
            dispatchOrderLines.add(dispatchOrderLine);
        }

        Test.startTest();
        String dispatchOrderId = ClassDispatchOrder.createDispatchOrder(purchaseOrderId, dispatchOrderLines);
        Dispatch_Order__c dispatchOrder = [SELECT State__c FROM Dispatch_Order__c WHERE Id =: dispatchOrderId];
        System.assertEquals('Pendiente de despacho', dispatchOrder.State__c, 'Dispatch Order not found or incorrect state was set');

        String exMessage = '';
        try{
            ClassDispatchOrder.cancelDispatchOrder(dispatchOrderId);
        } catch (Exception ex){
            exMessage = ex.getMessage();
        }

        System.assertEquals('', exMessage, 'Dispatch Order was not cancelled correctly. ' + exMessage);
        Test.stopTest();
    }

    @IsTest
    static void dispatchOrder(){
        Quote__c quote = TestSetup.createQuote();
        String purchaseOrderId = ClassPurchaseOrder.createPurchaseOrder(quote.Id, quote.Contact__c, null);
        List<Purchase_Order_Line__c> purchaseOrderLines = [SELECT Id FROM Purchase_Order_Line__c WHERE Purchase_Order__c =: purchaseOrderId];

        Dispatch_Order_Line__c dispatchOrderLine;
        List<Dispatch_Order_Line__c> dispatchOrderLines = new List<Dispatch_Order_Line__c>();
        for (Integer i = 0; i < purchaseOrderLines.size(); i++){
            dispatchOrderLine =  new Dispatch_Order_Line__c();
            dispatchOrderLine.Purchase_Order_Line__c = purchaseOrderLines[i].Id;
            dispatchOrderLine.Quantity__c = 9 + i;
            dispatchOrderLines.add(dispatchOrderLine);
        }
        String dispatchOrderId = ClassDispatchOrder.createDispatchOrder(purchaseOrderId, dispatchOrderLines);

        Test.startTest();
        ClassDispatchOrder.dispatchOrder(dispatchOrderId);
        Purchase_Order__c purchaseOrder = [SELECT Dispatch_Status__c FROM Purchase_Order__c WHERE Id =: purchaseOrderId];
        Dispatch_Order__c dispatchOrder = [SELECT State__c FROM Dispatch_Order__c WHERE Purchase_Order__c =: purchaseOrderId];
        System.assertEquals('Parcialmente', purchaseOrder.Dispatch_Status__c, 'Incorrect dispatch status from purchase order.');
        System.assertEquals('Despachada', dispatchOrder.State__c, 'Incorrect dispatch status from dispatch order.');

        //-- Second part of the test, check if the order was completly dispatched
        Dispatch_Order_Line__c dispatchOrderLine2;
        List<Dispatch_Order_Line__c> dispatchOrderLines2 = new List<Dispatch_Order_Line__c>();
        for (Integer i = 0; i < purchaseOrderLines.size(); i++){
            dispatchOrderLine2 =  new Dispatch_Order_Line__c();
            dispatchOrderLine2.Purchase_Order_Line__c = purchaseOrderLines[i].Id;
            dispatchOrderLine2.Quantity__c = 1;
            dispatchOrderLines2.add(dispatchOrderLine2);
        }
        String dispatchOrderId2 = ClassDispatchOrder.createDispatchOrder(purchaseOrderId, dispatchOrderLines2);

        ClassDispatchOrder.dispatchOrder(dispatchOrderId2);
        purchaseOrder = [SELECT Dispatch_Status__c FROM Purchase_Order__c WHERE Id =: purchaseOrderId];
        System.assertEquals('Completado', purchaseOrder.Dispatch_Status__c, 'Incorrect dispatch final status from purchase order.');
        
        String exMessage = '';
        try{
            ClassDispatchOrder.cancelDispatchOrder(dispatchOrder.Id);
        } catch (Exception ex){
            exMessage = ex.getMessage();
        }

        System.assertNotEquals('', exMessage, 'Dispatch Order did not throw the invoice exception.');
        Test.stopTest();
    }

    @IsTest
    static void getDispatchOrderLines(){
        Quote__c quote = TestSetup.createQuote();
        String purchaseOrderId = ClassPurchaseOrder.createPurchaseOrder(quote.Id, quote.Contact__c, null);
        List<Purchase_Order_Line__c> purchaseOrderLines = [SELECT Id FROM Purchase_Order_Line__c WHERE Purchase_Order__c =: purchaseOrderId];

        Dispatch_Order_Line__c dispatchOrderLine;
        List<Dispatch_Order_Line__c> dispatchOrderLines = new List<Dispatch_Order_Line__c>();
        for (Integer i = 0; i < purchaseOrderLines.size(); i++){
            dispatchOrderLine =  new Dispatch_Order_Line__c();
            dispatchOrderLine.Purchase_Order_Line__c = purchaseOrderLines[i].Id;
            dispatchOrderLine.Quantity__c = 9 + i;
            dispatchOrderLines.add(dispatchOrderLine);
        }
        String dispatchOrderId = ClassDispatchOrder.createDispatchOrder(purchaseOrderId, dispatchOrderLines);

        Test.startTest();
        List<Dispatch_Order_Line__c> expectedDispatchOrderLines = ClassDispatchOrder.getDispatchOrderLines(dispatchOrderId);
        System.assertEquals(3, expectedDispatchOrderLines.size(), 'Incorrect number of dispatch order lines retrieved.');
        Test.stopTest();
    }
}