force-app/main/default/objects/Dispatch_Order__c/Dispatch_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Despacho</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Despacho</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Ordenes de Despacho</relationshipLabel>
    <relationshipName>Dispatch_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/Dispatch_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Despacho</label>
    <nameField>
        <displayFormat>LOD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Despacho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Dispatch_Order__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Order__c</fullName>
    <label>Orden de Despacho</label>
    <referenceTo>Dispatch_Order__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Despacho</relationshipLabel>
    <relationshipName>Dispatch_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Linea de Orden de Compra</label>
    <referenceTo>Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Despacho</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Compra</label>
    <nameField>
        <displayFormat>LOC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Dispatched_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_Quantity__c</fullName>
    <label>Cantidad Despachada</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Lineas de Ordern de Compra</relationshipLabel>
    <relationshipName>Purchas_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Quote_Line__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClassDispatchOrder.cls
public with sharing class ClassDispatchOrder {
    @AuraEnabled
    public static Id createDispatchOrder(Id purchaseOrderId, List<Dispatch_Order_Line__c> dispatchOrderLines){
        try {    
            Dispatch_Order__c dispatchOrder = new Dispatch_Order__c();
            dispatchOrder.Purchase_Order__c = purchaseOrderId;
            insert(dispatchOrder);
        
            List<Id> purchasOrderLinesId = new List<Id>();
            for(Integer i = 0; i < dispatchOrderLines.size(); i++){
                dispatchOrderLines[i].Dispatch_Order__c = dispatchOrder.Id;
                purchasOrderLinesId.add(dispatchOrderLines[i].Purchase_Order_Line__c);
            }
            insert(dispatchOrderLines);

            Map<Id, Purchase_Order_Line__c> purchaseOrderLines = new Map<Id, Purchase_Order_Line__c>([
                SELECT Id, Dispatched_Quantity__c 
                FROM Purchase_Order_Line__c         
                WHERE Id IN : purchasOrderLinesId
            ]);

            String key;
            for(Integer i = 0; i < dispatchOrderLines.size(); i++){
                key = purchasOrderLinesId[i];
                purchaseOrderLines.get(key).Dispatched_Quantity__c += dispatchOrderLines[i].Quantity__c;
            }
            upsert(purchaseOrderLines.values());

            return dispatchOrder.Id;

        } catch(Exception e){
            throw new AuraHandledException('La orden de despacho no logró ser creada, por favor contactar al administrador del sistema.');
        }
    }
}