force-app/main/default/objects/Dispatch_Order__c/Dispatch_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Despacho</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Despacho</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Purchase_Order__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cuenta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Factura</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Ordenes de Despacho</relationshipLabel>
    <relationshipName>Ordenes_de_Despacho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Ordenes de Despacho</relationshipLabel>
    <relationshipName>Dispatch_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/Dispatch_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Despacho</label>
    <nameField>
        <displayFormat>LOD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Despacho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Dispatch_Order__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Order__c</fullName>
    <label>Orden de Despacho</label>
    <referenceTo>Dispatch_Order__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Despacho</relationshipLabel>
    <relationshipName>Dispatch_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Purchase_Order_Line__r.Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FAC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Id del cliente para la orden de compra</description>
    <label>No. de Orden</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credito</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <defaultValue>&quot;Al contado&quot;</defaultValue>
    <label>Condiciones de Pago</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClassInvoice.cls
public with sharing class ClassInvoice {
    @AuraEnabled
    public static EntityInvoice getPurchaseOrderInfo(String purchaseOrderId){
        List<Purchase_Order__c> purchaseOrderList = [
            SELECT
                Order_Id__c,
                Account__c,
                Quote__c
            FROM Purchase_Order__c
            WHERE Id =: purchaseOrderId
            LIMIT 1
        ];

        if(purchaseOrderList.size() <= 0){
            throw new AuraHandledException('Error: por favor contactar al administrador del sistema.');
        }

        Purchase_Order__c purchaseOrder = purchaseOrderList[0];
        System.debug(purchaseOrder);
        Quote__c quote = [SELECT Credit__c, Payment__c FROM Quote__c WHERE Id =: purchaseOrder.Quote__c LIMIT 1];
        System.debug(quote);
        Map<Id, Dispatch_Order__c> dispatchOrdersMap = new Map<Id, Dispatch_Order__c>([
            SELECT
                Id,
                Name
            FROM Dispatch_Order__c
            WHERE Purchase_Order__c =: purchaseOrderId
            AND Invoice__c = null
        ]);

        Set<Id> dispatchOrdersId = dispatchOrdersMap.keySet();
        List<Dispatch_Order__c> dispatchOrders = dispatchOrdersMap.values();
        System.debug(dispatchOrders);
        List<Dispatch_Order_Line__c> dispatchOrderLines = [
            SELECT
                Product_Name__c,
                //product all name and description formula
                Quantity__c
            FROM Dispatch_Order_Line__c
            WHERE Dispatch_Order__c IN  :dispatchOrdersId
        ];
        System.debug(dispatchOrderLines);
        
        EntityInvoice invoice = new EntityInvoice();
        invoice.quote = quote;
        invoice.purchaseOrder = purchaseOrder;
        invoice.dispatchOrders = dispatchOrders;
        invoice.dispatchOrderLines = dispatchOrderLines;
        System.debug(invoice);
        return invoice;
    }
}