force-app/main/default/objects/Price_Batch__c/Price_Batch__c.object-meta.xml
<CustomObject>
    <label>Lote de Precios</label>
    <nameField>
        <displayFormat>LPR-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Precios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Batch__c/fields/Converted__c.field-meta.xml
<CustomField>
    <fullName>Converted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convertido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Batch__c/fields/External_Shipping_GTQ__c.field-meta.xml
<CustomField>
    <fullName>External_Shipping_GTQ__c</fullName>
    <label>Flete Externo GTQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_Batch__c/fields/Taxes__c.field-meta.xml
<CustomField>
    <fullName>Taxes__c</fullName>
    <label>Impuestos Aduanales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/Price_Batch_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Lote de Precios</label>
    <nameField>
        <displayFormat>LLP-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Lote de Precios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Batch_Line__c/fields/Price_Batch__c.field-meta.xml
<CustomField>
    <fullName>Price_Batch__c</fullName>
    <label>Lote de Precios</label>
    <referenceTo>Price_Batch__c</referenceTo>
    <relationshipLabel>Lineas de Lote de Precios</relationshipLabel>
    <relationshipName>Lineas_de_Lote_de_Precios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Lote de Precios</relationshipLabel>
    <relationshipName>Lineas_de_Lote_de_Precios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>% Ganancia</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>% Flete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Taxes__c.field-meta.xml
<CustomField>
    <fullName>Taxes__c</fullName>
    <label>% Impuestos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Unit_Cost_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_GTQ__c</fullName>
    <label>Costo (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Unit_Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_USD__c</fullName>
    <label>Costo ($)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Unit_Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price_GTQ__c</fullName>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestBatch.cls
@IsTest
public class TestBatch {
    @TestSetup
    static void testSetup(){
        TestSetup.createProducts();
        Price_Batch__c batch = new Price_Batch__c();
        batch.Taxes__c = 0;
        batch.Dollar_Cost__c = 0;
        batch.Internal_Shipping__c = 0;
        batch.External_Shipping_GTQ__c = 0;
        batch.External_Shipping_USD__c = 0;
        insert batch;
    }

    static List<Price_Batch_Line__c> generateBatchLines(String batchId){
        List<Product__c> products = [SELECT Id FROM Product__c];
        List<Price_Batch_Line__c> batchLines = new List<Price_Batch_Line__c> ();
        Price_Batch_Line__c batchLine;

        batchLine = new Price_Batch_Line__c();
        batchLine.Price_Batch__c = batchId;
        batchLine.Shipping__c = 50;
        batchLine.Profit__c = 50;
        batchLine.Taxes__c = 50;
        batchLine.Quantity__c = 50;
        batchLine.Unit_Cost_USD__c = 0;
        batchLine.Unit_Cost_GTQ__c = 50;
        batchLine.Unit_Price_GTQ__c = 75;
        batchLine.Product__c = products[0].Id;
        batchLines.add(batchLine);

        batchLine = new Price_Batch_Line__c();
        batchLine.Price_Batch__c = batchId;
        batchLine.Shipping__c = 50;
        batchLine.Profit__c = 50;
        batchLine.Taxes__c = 50;
        batchLine.Quantity__c = 50;
        batchLine.Unit_Cost_USD__c = 0;
        batchLine.Unit_Cost_GTQ__c = 50;
        batchLine.Unit_Price_GTQ__c = 75;
        batchLine.Product__c = products[1].Id;
        batchLines.add(batchLine);

        return batchLines;
    }

    @IsTest
    static void saveBatch(){
        Price_Batch__c batch = [SELECT Id FROM Price_Batch__c LIMIT 1];
        List<Price_Batch_Line__c> batchLines = generateBatchLines(batch.Id);

        Test.startTest();
        ClassBatch.saveBatch(batch, batchLines);
        List<Price_Batch_Line__c> expectedBatchLines = [SELECT Id FROM Price_Batch_Line__c];
        System.assertEquals(expectedBatchLines.size(), batchLines.size(),'Incorrect number of lines created.');
        Test.stopTest();
    }

    @IsTest
    static void getBatch(){
        Price_Batch__c batch = [SELECT Id, Dollar_Cost__c FROM Price_Batch__c LIMIT 1];
        Test.startTest();
        Price_Batch__c expectedBatch = ClassBatch.getBatch(batch.Id);
        System.assertEquals(expectedBatch.Dollar_Cost__c, batch.Dollar_Cost__c, 'Incorrect batch retrieved.');
        Test.stopTest();
    }

    @IsTest
    static void getBatchLines(){
        Price_Batch__c batch = [SELECT Id, Dollar_Cost__c FROM Price_Batch__c LIMIT 1];
        List<Price_Batch_Line__c> batchLines = generateBatchLines(batch.Id);
        ClassBatch.saveBatch(batch, batchLines);
        Test.startTest();
        List<Price_Batch_Line__c> expectedBatchLines = ClassBatch.getBatchLines(batch.Id);
        System.assertEquals(expectedBatchLines.size(), batchLines.size(), 'Incorrect batch lines retrieved.');
        Test.stopTest();
    }

    @IsTest
    static void submitBatch(){
        Price_Batch__c batch = [
            SELECT Id, Taxes__c, Dollar_Cost__c, Internal_Shipping__c, External_Shipping_GTQ__c, External_Shipping_USD__c
            FROM Price_Batch__c
            LIMIT 1
        ];

        List<Price_Batch_Line__c> batchLines = generateBatchLines(batch.Id);
        Test.startTest();
        ClassBatch.submitBatch(batch, batchLines);
        batch = [SELECT Converted__c FROM Price_Batch__c LIMIT 1];
        System.assertEquals(true, batch.Converted__c, 'Batch not converted.');
        Test.stopTest();
    }
}