force-app/main/default/objects/Price_Batch__c/Price_Batch__c.object-meta.xml
<CustomObject>
    <label>Lote de Precios</label>
    <nameField>
        <displayFormat>LPR-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Precios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Batch__c/fields/Converted__c.field-meta.xml
<CustomField>
    <fullName>Converted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convertido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Batch__c/fields/External_Shipping_GTQ__c.field-meta.xml
<CustomField>
    <fullName>External_Shipping_GTQ__c</fullName>
    <label>Flete Externo GTQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_Batch__c/fields/Taxes__c.field-meta.xml
<CustomField>
    <fullName>Taxes__c</fullName>
    <label>Impuestos Aduanales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/Price_Batch_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Lote de Precios</label>
    <nameField>
        <displayFormat>LLP-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Lote de Precios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Batch_Line__c/fields/Price_Batch__c.field-meta.xml
<CustomField>
    <fullName>Price_Batch__c</fullName>
    <label>Lote de Precios</label>
    <referenceTo>Price_Batch__c</referenceTo>
    <relationshipLabel>Lineas de Lote de Precios</relationshipLabel>
    <relationshipName>Lineas_de_Lote_de_Precios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Lote de Precios</relationshipLabel>
    <relationshipName>Lineas_de_Lote_de_Precios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <formula>Product__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>% Ganancia</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Shipping__c.field-meta.xml
<CustomField>
    <fullName>Shipping__c</fullName>
    <label>% Flete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Taxes__c.field-meta.xml
<CustomField>
    <fullName>Taxes__c</fullName>
    <label>% Impuestos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Unit_Cost_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_GTQ__c</fullName>
    <label>Costo (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Unit_Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_USD__c</fullName>
    <label>Costo ($)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price_Batch_Line__c/fields/Unit_Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price_GTQ__c</fullName>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Precio de Producto</label>
    <nameField>
        <displayFormat>PRE-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Precios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Dollar_Cost__c.field-meta.xml
<CustomField>
    <fullName>Dollar_Cost__c</fullName>
    <label>Compra de Dolar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/External_Shipping__c.field-meta.xml
<CustomField>
    <fullName>External_Shipping__c</fullName>
    <label>Flete Externo GTQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/External_Shipping_USD__c.field-meta.xml
<CustomField>
    <fullName>External_Shipping_USD__c</fullName>
    <label>Flete Externo USA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Internal_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Internal_Shipping__c</fullName>
    <label>Flete Interno</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Price_Batch__c.field-meta.xml
<CustomField>
    <fullName>Price_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote de Precios</label>
    <referenceTo>Price_Batch__c</referenceTo>
    <relationshipLabel>Precios</relationshipLabel>
    <relationshipName>Precios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Precios</relationshipLabel>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Margen de Ganancia</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Cost_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_GTQ__c</fullName>
    <label>Costo Unitario en Quetzales</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Cost_USD__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_USD__c</fullName>
    <label>Costo Unitario en Dolares</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price_GTQ__c</fullName>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClassBatch.cls
public with sharing class ClassBatch {
    @AuraEnabled
    public static void submitBatch(Price_Batch__c batch, List<Price_Batch_Line__c> batchLines){
        List<Price_Batch_Line__c> batchLinesToDelete = [SELECT Id
                                                    FROM Price_Batch_Line__c
                                                    WHERE Id NOT IN : batchLines AND Price_Batch__c =: batch.Id];
        delete batchLinesToDelete;
        upsert batchLines;

        batch.Converted__c = true;
        update batch;

        Product_Price__c price;
        List<Product_Price__c> prices = new List<Product_Price__c>();
        for(Price_Batch_Line__c batchLine : batchLines){
            price = new Product_Price__c();
            price.Quantity__c = batchLine.Quantity__c;
            price.Dollar_Cost__c = batch.Dollar_Cost__c;
            price.Unit_Cost_USD__c = batchLine.Unit_Cost_USD__c;
            price.Unit_Cost_GTQ__c = batchLine.Unit_Cost_GTQ__c;
            price.External_Shipping__c = batch.External_Shipping_GTQ__c * batchLine.Shipping__c / 100;
            price.External_Shipping_USD__c = batch.External_Shipping_USD__c * batchLine.Shipping__c / 100;
            price.Internal_Shipping__c = batch.Internal_Shipping__c * batchLine.Shipping__c / 100;
            price.Taxes__c = batch.Taxes__c * batchLine.Taxes__c / 100;
            price.Profit__c = batchLine.Profit__c;
            price.Unit_Price_GTQ__c = batchLine.Unit_Price_GTQ__c;
            price.Product__c = batchLine.Product__c;
            price.Price_Batch__c = batch.Id;
            prices.add(price);
        }

        insert(prices);
    }

    @AuraEnabled
    public static void saveBatch(Price_Batch__c batch, List<Price_Batch_Line__c> batchLines){
        List<Price_Batch_Line__c> batchLinesToDelete = [SELECT Id
                                                    FROM Price_Batch_Line__c
                                                    WHERE Id NOT IN : batchLines AND Price_Batch__c =: batch.Id];
        delete batchLinesToDelete;
        upsert batchLines;
    }

    @AuraEnabled
    public static Price_Batch__c getBatch(String batchId){
        return [SELECT  Taxes__c,
                        Converted__c,
                        Dollar_Cost__c,
                        Internal_Shipping__c,
                        External_Shipping_GTQ__c,
                        External_Shipping_USD__c
                FROM Price_Batch__c
                WHERE Id =: batchId];
    }

    @AuraEnabled
    public static List<Price_Batch_Line__c> getBatchLines(String batchId){
        return [SELECT  Id,
                        Quantity__c,
                        Unit_Cost_USD__c,
                        Unit_Cost_GTQ__c,
                        Shipping__c,
                        Taxes__c,
                        Profit__c,
                        Unit_Price_GTQ__c,
                        Product__c,
                        Product_Name__c,
                        Product_Description__c,
                        Price_Batch__c
                FROM Price_Batch_Line__c
                WHERE Price_Batch__c =: batchId];
    }
}