force-app/main/default/objects/Company_Information__mdt/Company_Information__mdt.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <pluralLabel>Company Information</pluralLabel>
</CustomObject>

force-app/main/default/objects/Company_Information__mdt/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Dirección</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_Anulation_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Infile_Anulation_Endpoint__c</fullName>
    <label>Endpoint de Anulación</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_Certification_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Infile_Certification_Endpoint__c</fullName>
    <label>Endpoint de Certificación</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_Certification_Key__c.field-meta.xml
<CustomField>
    <fullName>Infile_Certification_Key__c</fullName>
    <label>Llave de Certificación</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_NIT__c.field-meta.xml
<CustomField>
    <fullName>Infile_NIT__c</fullName>
    <label>NIT en Infile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_NIT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Infile_NIT_Endpoint__c</fullName>
    <label>Endpoint de Consulta de NIT</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_Sign_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Infile_Sign_Endpoint__c</fullName>
    <label>Endpoint de Firma</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_Sign_Key__c.field-meta.xml
<CustomField>
    <fullName>Infile_Sign_Key__c</fullName>
    <label>Llave de Firma</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Infile_User__c.field-meta.xml
<CustomField>
    <fullName>Infile_User__c</fullName>
    <label>Usuario Infile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Invoice_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email__c</fullName>
    <label>Correo de envio de facturas</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <label>Nombre Legal</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/NIT__c.field-meta.xml
<CustomField>
    <fullName>NIT__c</fullName>
    <label>NIT</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispatch_Order_Line__c/Dispatch_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Despacho</label>
    <nameField>
        <displayFormat>LOD-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Despacho</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispatch_Order_Line__c/fields/Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Linea de Orden de Compra</label>
    <referenceTo>Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Despacho</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FAC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anulada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Motivo de Anulación</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoría</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordenes de Despacho</fullName>
                <default>true</default>
                <label>Ordenes de Despacho</label>
            </value>
            <value>
                <fullName>Monto Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Moneda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GTQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Fecha</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Dispatch_Orders__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Orders__c</fullName>
    <label>Ordenes de Despacho</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Purchase_Orders_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>TEXT(Quote__r.Currency_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moneda</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Compra</label>
    <nameField>
        <displayFormat>LOC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Lineas de Ordern de Compra</relationshipLabel>
    <relationshipName>Purchas_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Quote_Line__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe estar relacionado a la cuenta seleccionada.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <defaultValue>&quot;GTQ&quot;</defaultValue>
    <label>Moneda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GTQ</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestInvoice.cls
@IsTest
public class TestInvoice {
    @IsTest
    static void getPurchaseOrderInfo(){
        Quote__c quote = TestSetup.createQuote();
        String purchaseOrderId = ClassPurchaseOrder.createPurchaseOrder(quote.Id, quote.Contact__c, null);
        Test.startTest();
        ClassInvoice.EntityInvoice purchaseOrderInfo = ClassInvoice.getPurchaseOrderInfo(purchaseOrderId);
        System.assertEquals(quote.Id, purchaseOrderInfo.quote.Id, 'Invalid quote retrieved.');

        ClassInvoice.EntityLegalInformation legalInfo = ClassInvoice.getClientLegalInformation('12345678', purchaseOrderInfo.companyInfo);
        System.assertEquals(true, String.isNotBlank(legalInfo.legalName), 'Legal info not retrieved.');
        
        String exceptionMsg = null;
        try {
            ClassInvoice.EntityInvoice purchaseOrderInfoInvalid = ClassInvoice.getPurchaseOrderInfo('Invalid Id retrieved.');
        } catch (Exception ex){
            exceptionMsg = ex.getMessage();
        }

        System.assertNotEquals(null, exceptionMsg, 'Invalid purchase Id must throw an exception.');
        Test.stopTest();
    }

    @IsTest
    static void createInvoice(){
        Quote__c quote = TestSetup.createQuote();
        String purchaseOrderId = ClassPurchaseOrder.createPurchaseOrder(quote.Id, quote.Contact__c, null);
        List<Purchase_Order_Line__c> purchaseOrderLines = [SELECT Id FROM Purchase_Order_Line__c WHERE Purchase_Order__c =: purchaseOrderId];

        Dispatch_Order_Line__c dispatchOrderLine;
        List<Dispatch_Order_Line__c> dispatchOrderLines = new List<Dispatch_Order_Line__c>();
        for (Integer i = 0; i < purchaseOrderLines.size(); i++){
            dispatchOrderLine =  new Dispatch_Order_Line__c();
            dispatchOrderLine.Purchase_Order_Line__c = purchaseOrderLines[i].Id;
            dispatchOrderLine.Quantity__c = 9 + i;
            dispatchOrderLines.add(dispatchOrderLine);
        }

        String dispatchOrderId = ClassDispatchOrder.createDispatchOrder(purchaseOrderId, dispatchOrderLines);
        Invoice__c invoice = new Invoice__c();
        invoice.Date__c = Date.today();
        invoice.Currency_Code__c = 'GTQ';
        invoice.Category__c = 'Ordenes de Despacho';
        invoice.Purchase_Order__c = purchaseOrderId;
        invoice.Dispatch_Orders__c = dispatchOrderId;
        String xml = '{total}{iva}{items}';

        Test.startTest();
        ClassInvoice.EntityInvoiceWrapper wrapper = ClassInvoice.getInvoiceWrapper(invoice, xml);
        System.assertEquals(true, String.isNotBlank(wrapper.xmlEncoded), 'Empty xmlEncoded response.');
        String invoiceId;
        String exMessage;
        try{
            invoiceId = ClassInvoice.insertInvoiceApex(wrapper.invoice, wrapper.purchaseOrder, wrapper.dispatchOrders);
        } catch(Exception ex){
            exMessage = ex.getMessage();
        } 
        System.assertEquals(true, String.isBlank(exMessage), 'Exception thrown: ' + exMessage);
        System.assertEquals(true, String.isNotBlank(invoiceId), 'Invoice not created.');

        ClassInvoice.cancelInvoiceApex(invoiceId,'Test Reasson');
        invoice = [SELECT Canceled__c, Cancellation_Reason__c FROM Invoice__c WHERE Id =: invoiceId];
        System.assertEquals(true, invoice.Canceled__c, 'Invoice not cancelled correctly.');
        System.assertEquals('Test Reasson', invoice.Cancellation_Reason__c, 'Incorrect cancel reasson retrieved.');
        ClassInvoice.EntityCanelInvoiceInformation response = ClassInvoice.getInvoiceInformation(invoiceId);
        System.assertEquals(invoiceId, response.invoice.Id, 'Incorrect invoice retrieved.');
        Test.stopTest();
    }

    @IsTest
    static void externalCalls(){
        Company_Information__mdt companyInfo = [
            SELECT
                Label,
                Legal_Name__c,
                NIT__c,
                Address__c,
                Invoice_Email__c,
                Infile_User__c,
                Infile_NIT__c,
                Infile_Sign_Key__c,
                Infile_Sign_Endpoint__c,
                Infile_Certification_Key__c,
                Infile_Certification_Endpoint__c,
                Infile_Anulation_Endpoint__c,
                Infile_NIT_Endpoint__c
            FROM Company_Information__mdt
            LIMIT 1
        ];

        ClassInvoice.EntitySignInvoiceResponse signInvoiceResponse = ClassInvoice.signInvoice('', companyInfo, true );
        System.assertEquals(true, signInvoiceResponse.resultado, 'Invalid result.');

        EntityInvoiceResponse processInvoiceResponse = ClassInvoice.processInvoice('', companyInfo, '', '', false);
        System.assertEquals(true, processInvoiceResponse.resultado, 'Invalid result.');
    }
}