force-app/main/default/objects/Account/fields/NIT__c.field-meta.xml
<CustomField>
    <fullName>NIT__c</fullName>
    <label>NIT</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/Company_Information__mdt.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <pluralLabel>Company Information</pluralLabel>
</CustomObject>

force-app/main/default/objects/Company_Information__mdt/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Dirección</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <label>Nombre Legal</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/NIT__c.field-meta.xml
<CustomField>
    <fullName>NIT__c</fullName>
    <label>NIT</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Information__mdt/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Teléfono</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Price_GTQ__c</fullName>
    <formula>Related_Price__r.Unit_Price_GTQ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price_USD__c.field-meta.xml
<CustomField>
    <fullName>Price_USD__c</fullName>
    <formula>Related_Price__r.Unit_Price_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe estar relacionado a la cuenta seleccionada.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <defaultValue>&quot;GTQ&quot;</defaultValue>
    <label>Moneda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GTQ</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Tiempo de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Offer_Time__c.field-meta.xml
<CustomField>
    <fullName>Offer_Time__c</fullName>
    <defaultValue>15</defaultValue>
    <label>Validez de Oferta (Días)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <defaultValue>&quot;Al contado&quot;</defaultValue>
    <label>Condiciones de Pago</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <label>Vendedor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Users</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>IF( ISPICKVAL(Currency_Code__c, &apos;GTQ&apos;),  Total_GTQ__c * (1 - Discount__c), Total_USD__c * (1 - Discount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Total_GTQ__c</fullName>
    <label>Total GTQ</label>
    <summarizedField>Quote_Line__c.Subtotal_GTQ__c</summarizedField>
    <summaryForeignKey>Quote_Line__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_In_Letters__c.field-meta.xml
<CustomField>
    <fullName>Total_In_Letters__c</fullName>
    <label>Total en letras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_USD__c</fullName>
    <label>Total USD</label>
    <summarizedField>Quote_Line__c.Subtotal_USD__c</summarizedField>
    <summaryForeignKey>Quote_Line__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Cotización</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Cotización</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Tiempo de entrega</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Subtotal_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_GTQ__c</fullName>
    <label>Importe GTQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Subtotal_USD__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_USD__c</fullName>
    <label>Importe USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sales_Users.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sala de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Rosa María López</fullName>
    </customValue>
    <customValue>
        <fullName>Hugo Rolando López</fullName>
    </customValue>
    <masterLabel>Vendedores</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteController.cls
public with sharing class QuoteController {
    public Quote__c quote {get;set;}
    public Contact contact {get;set;}
    public Account account {get;set;}
    public List<Quote_Line__c> childLines {get;set;}
    public List<Quote_Line__c> fatherLines {get;set;}
    public Company_Information__mdt company {get;set;}
    public List<Integer> rowspanList {get; set;}
    public String todaysDate {get; set;}
    
    public QuoteController(ApexPages.StandardController stdController) {
        Id quoteId = stdController.getRecord().Id;
        quote = [SELECT Name, 
                        Discount__c, 
                        Currency_Code__c, 
                        Account__c, 
                        Contact__c, 
                        Total__c,
                        Total_GTQ__c,
                        Total_USD__c,
                        Total_In_Letters__c,
                        Delivery_Time__c,
                        Offer_Time__c,
                        Payment__c,
                        Delivery_Address__c,
                        Sales_User__c 
                 FROM Quote__c WHERE Id =: quoteId LIMIT 1];
        account = [SELECT Name, 
                          ShippingAddress, 
                          Phone,
                          NIT__c
                   FROM Account WHERE Id =: quote.Account__c LIMIT 1];
        contact = [SELECT Name FROM Contact WHERE Id =: quote.Contact__c LIMIT 1];
        fatherLines = [SELECT Name, 
                             Delivery_Time__c, 
                             Description__c, 
                             Quantity__c,
                             Subtotal_GTQ__c, 
                             Subtotal_USD__c, 
                             Type__c,
                             Product__c,
                             Product__r.Name,
                             Product__r.Price_USD__c, 
                             Product__r.Price_GTQ__c
                      FROM Quote_Line__c 
                      WHERE Quote__c =: quoteId AND Type__c != 'Child'
                      ORDER BY Index__c ASC];
        childLines = [SELECT Name, 
                             Delivery_Time__c, 
                             Description__c, 
                             Quantity__c,
                             Subtotal_GTQ__c, 
                             Subtotal_USD__c, 
                             Type__c,
                             Product__c,
                             Product__r.Price_USD__c, 
                             Product__r.Price_GTQ__c
                      FROM Quote_Line__c 
                      WHERE Quote__c =: quoteId AND Type__c = 'Child'
                      ORDER BY Index__c ASC];
        company = [SELECT Legal_Name__c, 
                          Phone__c, 
                          Address__c, 
                          NIT__c 
                   FROM Company_Information__mdt LIMIT 1];

       List<String> months = new List<String>{'enero', 'febrero', 'marzo', 'abril', 
       'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'};

       Integer day = System.today().day();
       String month = months[System.today().month() - 1];
       Integer year = System.today().year();
       todaysDate = String.valueOf(day) + ' de ' + month + ' de ' + String.valueOf(year);
    }
}