force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Authorization_Contact__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Autorizado por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes de Compra Autorizadas</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Purchase_Orders_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <label>Dirección de Entrega</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Dispatch_Status__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Status__c</fullName>
    <label>Estado de Despacho</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Parcialmente</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Estado de Facturación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Parcialmente</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Id del cliente para la orden de compra</description>
    <label>No. de Orden</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Ordenes de Compra</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Orden de Compra</label>
    <nameField>
        <displayFormat>LOC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Orden de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <formula>Quote_Line__r.Delivery_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiempo de Entrega</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Dispatch_Pending_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Pending_Quantity__c</fullName>
    <label>Cantidad Pendiente de Despacho</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Dispatched_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_Quantity__c</fullName>
    <label>Cantidad Despachada</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Quote_Line__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código del Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Quote_Line__r.Product__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción del Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Lineas de Ordern de Compra</relationshipLabel>
    <relationshipName>Purchas_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Quote_Line__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Linea de Cotización</label>
    <referenceTo>Quote_Line__c</referenceTo>
    <relationshipLabel>Lineas de Orden de Compra</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <formula>Quote_Line__r.Product__r.Stock__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe estar relacionado a la cuenta seleccionada.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Converted__c.field-meta.xml
<CustomField>
    <fullName>Converted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convertida a Orden de Trabajo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Tiempo de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Cotización</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Cotización</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Tiempo de entrega</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClassPurchaseOrder.cls
public with sharing class ClassPurchaseOrder {

    @AuraEnabled
    public static Id createPurchaseOrder(String quoteId, String contactId, String orderId){
        Quote__c quote;
        List<Quote__c> quotes = [SELECT Contact__c, Account__c, Delivery_Address__c, Converted__c
                          FROM Quote__c
                          WHERE Id =: quoteId
                          LIMIT 1];

        if(quotes == null || quotes.size() <= 0){
            throw new AuraHandledException('No se encontro ninguna Cotización.');
        } else {
            quote = quotes[0];
        }

        quote.Converted__c = true;
        update(quote);

        Purchase_Order__c purchaseOrder = new Purchase_Order__c();
        purchaseOrder.Quote__c = quoteId;
        purchaseOrder.Contact__c = quote.Contact__c;
        purchaseOrder.Account__c = quote.Account__c;
        purchaseOrder.Delivery_Address__c = quote.Delivery_Address__c;
        purchaseOrder.Authorization_Contact__c = contactId;
        purchaseOrder.Order_Id__c = orderId;
        purchaseOrder.Invoice_Status__c = 'Pendiente';
        purchaseOrder.Dispatch_Status__c = 'Pendiente';
        insert(purchaseOrder);

        List<Quote_Line__c> quoteLines = [SELECT Id
                                          FROM Quote_Line__c
                                          WHERE Quote__c =: quoteId
                                          AND Type__c != 'Father'
                                          ORDER BY Index__c ASC];

        List<Purchase_Order_Line__c> purchaseOrderLines = new List<Purchase_Order_Line__c>();
        Purchase_Order_Line__c purchaseOrderLine;

        for(Quote_Line__c quoteLine : quoteLines){
            purchaseOrderLine = new Purchase_Order_Line__c();
            purchaseOrderLine.Purchase_Order__c = purchaseOrder.Id;
            purchaseOrderLine.Quote_Line__c = quoteLine.Id;
            purchaseOrderLine.Dispatched_Quantity__c = 0;
            purchaseOrderLine.Dispatch_Pending_Quantity__c = 0;
            purchaseOrderLines.add(purchaseOrderLine);
        }
        insert(purchaseOrderLines);
        return purchaseOrder.Id;
    }

    @AuraEnabled
    public static List<Purchase_Order_Line__c> getPurchaseOrderLines(String purchaseOrderId){
        return [SELECT  Id,
                        Product__c,
                        Product_Name__c,
                        Quantity__c,
                        Dispatched_Quantity__c,
                        Dispatch_Pending_Quantity__c,
                        Delivery_Time__c,
                        Stock__c
                FROM Purchase_Order_Line__c
                WHERE Purchase_Order__c =: purchaseOrderId];
    }
}