force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Familia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Related_Price__c.field-meta.xml
<CustomField>
    <fullName>Related_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Precio Relacionado</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El precio seleccionado no corresponde al producto.</errorMessage>
        <filterItems>
            <field>Product_Price__c.Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock_Maximum__c.field-meta.xml
<CustomField>
    <fullName>Stock_Maximum__c</fullName>
    <label>Stock Máximo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Stock_Minimum__c</fullName>
    <label>Stock Mínimo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Subfamily__c.field-meta.xml
<CustomField>
    <fullName>Subfamily__c</fullName>
    <label>Subfamilia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Subfamily</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unidad de Medida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamily__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Precio de Producto</label>
    <nameField>
        <displayFormat>PRE-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Precios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Precios</relationshipLabel>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Margen de Ganancia</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Cost_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_GTQ__c</fullName>
    <label>Costo Unitario en Quetzales</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price_GTQ__c</fullName>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe estar relacionado a la cuenta seleccionada.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <defaultValue>&quot;GTQ&quot;</defaultValue>
    <label>Moneda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GTQ</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Offer_Time__c.field-meta.xml
<CustomField>
    <fullName>Offer_Time__c</fullName>
    <defaultValue>15</defaultValue>
    <label>Validez de Oferta (Días)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <defaultValue>&quot;Al contado&quot;</defaultValue>
    <label>Condiciones de Pago</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Sales_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_User__c</fullName>
    <label>Vendedor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Users</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line__c/Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Cotización</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Cotización</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marca</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Familia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Precio de Producto</label>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Subfamily__c.field-meta.xml
<CustomField>
    <fullName>Subfamily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subfamilia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Subtotal_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_GTQ__c</fullName>
    <label>Importe GTQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Subtotal_USD__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_USD__c</fullName>
    <label>Importe USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Tiempo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Micro 100</fullName>
    </customValue>
    <customValue>
        <fullName>Fandher</fullName>
    </customValue>
    <customValue>
        <fullName>Flexitallic</fullName>
    </customValue>
    <customValue>
        <fullName>Workland</fullName>
    </customValue>
    <customValue>
        <fullName>General Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Kana</fullName>
    </customValue>
    <customValue>
        <fullName>Mausa</fullName>
    </customValue>
    <customValue>
        <fullName>Dedini</fullName>
    </customValue>
    <customValue>
        <fullName>Imbil</fullName>
    </customValue>
    <customValue>
        <fullName>Resonance</fullName>
    </customValue>
    <customValue>
        <fullName>Stanley</fullName>
    </customValue>
    <customValue>
        <fullName>Kestra</fullName>
    </customValue>
    <customValue>
        <fullName>Greenfield</fullName>
    </customValue>
    <customValue>
        <fullName>Cleveland</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago Latrobe</fullName>
    </customValue>
    <customValue>
        <fullName>Incor</fullName>
    </customValue>
    <customValue>
        <fullName>Genérico</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sellos Hidráulicos</fullName>
    </customValue>
    <customValue>
        <fullName>Cadena Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Herramienta de Corte</fullName>
    </customValue>
    <customValue>
        <fullName>Promocional</fullName>
    </customValue>
    <customValue>
        <fullName>Calzado Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Repuestos</fullName>
    </customValue>
    <customValue>
        <fullName>Soldadura</fullName>
    </customValue>
    <customValue>
        <fullName>Herramienta Manual</fullName>
    </customValue>
    <masterLabel>Familia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Users.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sala de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Rosa María López</fullName>
    </customValue>
    <customValue>
        <fullName>Hugo Rolando López</fullName>
    </customValue>
    <masterLabel>Vendedores</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Subfamily.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Espirometálico tipo CG</fullName>
    </customValue>
    <customValue>
        <fullName>Espirometálico tipo CGI</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo RC</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Domo</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Oval</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Empaque</fullName>
    </customValue>
    <customValue>
        <fullName>Estopa</fullName>
    </customValue>
    <customValue>
        <fullName>Regalo para cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Catálogo</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71820</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71821</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71822</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71823</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71824</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71825</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71826</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71827</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71828</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71829</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71830</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71831</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71832</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71833</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71834</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71835</fullName>
    </customValue>
    <customValue>
        <fullName>Buril de Tungsteno</fullName>
    </customValue>
    <customValue>
        <fullName>Buril de Cobalto</fullName>
    </customValue>
    <customValue>
        <fullName>Rodos</fullName>
    </customValue>
    <customValue>
        <fullName>Pines</fullName>
    </customValue>
    <customValue>
        <fullName>Bujes</fullName>
    </customValue>
    <customValue>
        <fullName>Cortador Vertical</fullName>
    </customValue>
    <masterLabel>Subfamilia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unidad</fullName>
    </customValue>
    <customValue>
        <fullName>Par</fullName>
    </customValue>
    <customValue>
        <fullName>Caja 5 pies</fullName>
    </customValue>
    <customValue>
        <fullName>Caja 10 pies</fullName>
    </customValue>
    <customValue>
        <fullName>Juego</fullName>
    </customValue>
    <customValue>
        <fullName>Libra</fullName>
    </customValue>
    <masterLabel>Unidad de Medida</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestSetup.cls
@IsTest
public class TestSetup {
    public static List<Product__c> createProducts(){
        List<Product__c> products = new List<Product__c>();
        Product__c product;

        product = new Product__c();
        product.Description__c = 'Sello Espirometálico 1" 900-1500 PSI';
        product.Brand__c = 'Flexitallic';
        product.Family__c = 'Sellos Hidráulicos';
        product.Subfamily__c = 'Espirometálico tipo CG';
        product.Unit__c = 'Unidad';
        product.Stock__c = 50;
        product.Stock_Minimum__c = 0;
        product.Stock_Maximum__c = 100;
        products.add(product);

        product = new Product__c();
        product.Description__c = 'Sierras';
        product.Brand__c = 'Genérico';
        product.Family__c = 'Herramienta de Corte';
        product.Subfamily__c = 'Cortador Vertical';
        product.Unit__c = 'Unidad';
        product.Stock__c = 50;
        product.Stock_Minimum__c = 0;
        product.Stock_Maximum__c = 100;
        products.add(product);

        product = new Product__c();
        product.Description__c = 'Buril de Cobalto';
        product.Brand__c = 'Micro 100';
        product.Family__c = 'Herramienta de Corte';
        product.Subfamily__c = 'Buril de Cobalto';
        product.Unit__c = 'Unidad';
        product.Stock__c = 50;
        product.Stock_Minimum__c = 0;
        product.Stock_Maximum__c = 100;
        products.add(product);

        insert products;

        List<Product_Price__c> prices = new List<Product_Price__c>();
        Product_Price__c price = new Product_Price__c();
        price.Quantity__c = 5;
        price.Profit__c = 50;
        price.Unit_Cost_GTQ__c = 100;
        price.Unit_Price_GTQ__c = 150;
        price.Product__c = products[0].Id;
        prices.add(price);

        price = new Product_Price__c();
        price.Quantity__c = 6;
        price.Profit__c = 50;
        price.Unit_Cost_GTQ__c = 200;
        price.Unit_Price_GTQ__c = 300;
        price.Product__c = products[1].Id;
        prices.add(price);

        price = new Product_Price__c();
        price.Quantity__c = 7;
        price.Profit__c = 50;
        price.Unit_Cost_GTQ__c = 400;
        price.Unit_Price_GTQ__c = 600;
        price.Product__c = products[2].Id;
        prices.add(price);

        insert prices;

        products[0].Related_Price__c = prices[0].Id;
        products[1].Related_Price__c = prices[1].Id;
        products[2].Related_Price__c = prices[2].Id;

        update products;

        return products;
    }

    public static Quote__c createQuote(){
        String i = getUUID();
        Account account = new Account(Name = 'Ingenio Magdalena - ' + i);
        insert account;

        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.FirstName = 'Hugo';
        contact.LastName = 'López - ' + i;
        insert contact;

        Quote__c quote = new Quote__c();
        quote.Account__c = account.Id;
        quote.Contact__c = contact.Id;
        quote.Currency_Code__c = 'GTQ';
        quote.Payment__c = 'Al contado';
        quote.Offer_Time__c = 15;
        quote.Sales_User__c = 'Sala de Ventas';
        insert quote;

        List<Product__c> products = TestSetup.createProducts();
        List<Quote_Line__c> quoteLines =  new List<Quote_Line__c>();
        Quote_Line__c quoteLine;

        quoteLine = new Quote_Line__c();
        quoteLine.Quantity__c = 10;
        quoteLine.Quote__c = quote.Id;
        quoteLine.Index__c = 0;
        quoteLine.Product__c = products[0].Id;
        quoteLine.Product_Price__c = products[0].Related_Price__c;
        quoteLine.Time__c = 10;
        quoteLine.Type__c = 'Normal';
        quoteLine.Subtotal_GTQ__C = 10*150;
        quoteLine.Subtotal_USD__C = 15;
        quoteLines.add(quoteLine);

        quoteLine = new Quote_Line__c();
        quoteLine.Quantity__c = 11;
        quoteLine.Quote__c = quote.Id;
        quoteLine.Index__c = 1;
        quoteLine.Product__c = products[1].Id;
        quoteLine.Product_Price__c = products[1].Related_Price__c;
        quoteLine.Time__c = 11;
        quoteLine.Type__c = 'Normal';
        quoteLine.Subtotal_GTQ__C = 11*300;
        quoteLine.Subtotal_USD__C = 15;
        quoteLines.add(quoteLine);

        quoteLine = new Quote_Line__c();
        quoteLine.Quantity__c = 12;
        quoteLine.Quote__c = quote.Id;
        quoteLine.Index__c = 2;
        quoteLine.Product__c = products[2].Id;
        quoteLine.Product_Price__c = products[2].Related_Price__c;
        quoteLine.Time__c = 12;
        quoteLine.Type__c = 'Normal';
        quoteLine.Subtotal_GTQ__C = 12*600;
        quoteLine.Subtotal_USD__C = 15;
        quoteLines.add(quoteLine);

        insert quoteLines;
        return quote;
    }

    public static String getUUID()
    {
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        system.debug(guid);
        return guid;
    }
}