force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Dimensions__c.field-meta.xml
<CustomField>
    <fullName>Dimensions__c</fullName>
    <label>Dimensiones</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Familia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Inventory_State__c.field-meta.xml
<CustomField>
    <fullName>Inventory_State__c</fullName>
    <formula>IF( Stock__c &lt; (Stock_Maximum__c -  Stock_Minimum__c) * 0.15 , &quot;Solicitar Material&quot;, 
 IF( Stock__c &lt; (Stock_Maximum__c -  Stock_Minimum__c) * 0.50 , &quot;Planificar Pedido&quot;, &quot;Inventario Suficiente&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estado en Inventario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamily__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Old_Code__c.field-meta.xml
<CustomField>
    <fullName>Old_Code__c</fullName>
    <label>Código Anterior</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Price_GTQ__c</fullName>
    <formula>Related_Price__r.Unit_Price_GTQ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price_USD__c.field-meta.xml
<CustomField>
    <fullName>Price_USD__c</fullName>
    <formula>Related_Price__r.Unit_Price_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Subfamily__c.field-meta.xml
<CustomField>
    <fullName>Subfamily__c</fullName>
    <label>Subfamilia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Subfamily</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unidad de Medida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamily__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Converted__c.field-meta.xml
<CustomField>
    <fullName>Converted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convertida a Orden de Trabajo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <defaultValue>&quot;GTQ&quot;</defaultValue>
    <label>Moneda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GTQ</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Tiempo de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_In_Letters__c.field-meta.xml
<CustomField>
    <fullName>Total_In_Letters__c</fullName>
    <label>Total en letras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Cotización</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Cotización</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marca</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Tiempo de entrega</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Dimensions__c.field-meta.xml
<CustomField>
    <fullName>Dimensions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimensiones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Familia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Material</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Old_Code__c.field-meta.xml
<CustomField>
    <fullName>Old_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Código Anterior</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Subfamily__c.field-meta.xml
<CustomField>
    <fullName>Subfamily__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subfamilia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Tiempo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Time_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tiempo en días</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Discount_Max__c.field-meta.xml
<CustomField>
    <fullName>Discount_Max__c</fullName>
    <label>Descuento Autorizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Micro 100</fullName>
    </customValue>
    <customValue>
        <fullName>Fandher</fullName>
    </customValue>
    <customValue>
        <fullName>Flexitallic</fullName>
    </customValue>
    <customValue>
        <fullName>Workland</fullName>
    </customValue>
    <customValue>
        <fullName>General Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Kana</fullName>
    </customValue>
    <customValue>
        <fullName>Mausa</fullName>
    </customValue>
    <customValue>
        <fullName>Dedini</fullName>
    </customValue>
    <customValue>
        <fullName>Imbil</fullName>
    </customValue>
    <customValue>
        <fullName>Resonance</fullName>
    </customValue>
    <customValue>
        <fullName>Stanley</fullName>
    </customValue>
    <customValue>
        <fullName>Kestra</fullName>
    </customValue>
    <customValue>
        <fullName>Greenfield</fullName>
    </customValue>
    <customValue>
        <fullName>Cleveland</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago Latrobe</fullName>
    </customValue>
    <customValue>
        <fullName>Incor</fullName>
    </customValue>
    <customValue>
        <fullName>Genérico</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sellos Hidráulicos</fullName>
    </customValue>
    <customValue>
        <fullName>Cadena Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Herramienta de Corte</fullName>
    </customValue>
    <customValue>
        <fullName>Promocional</fullName>
    </customValue>
    <customValue>
        <fullName>Calzado Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Repuestos</fullName>
    </customValue>
    <customValue>
        <fullName>Soldadura</fullName>
    </customValue>
    <customValue>
        <fullName>Herramienta Manual</fullName>
    </customValue>
    <masterLabel>Familia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Material.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acero 304</fullName>
    </customValue>
    <customValue>
        <fullName>Acero 316</fullName>
    </customValue>
    <customValue>
        <fullName>Tungsteno</fullName>
    </customValue>
    <customValue>
        <fullName>Cobalto</fullName>
    </customValue>
    <masterLabel>Material</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Subfamily.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Espirometálico tipo CG</fullName>
    </customValue>
    <customValue>
        <fullName>Espirometálico tipo CGI</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo RC</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Domo</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Oval</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Empaque</fullName>
    </customValue>
    <customValue>
        <fullName>Estopa</fullName>
    </customValue>
    <customValue>
        <fullName>Regalo para cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Catálogo</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71820</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71821</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71822</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71823</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71824</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71825</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71826</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71827</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71828</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71829</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71830</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71831</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71832</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71833</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71834</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71835</fullName>
    </customValue>
    <customValue>
        <fullName>Buril de Tungsteno</fullName>
    </customValue>
    <customValue>
        <fullName>Buril de Cobalto</fullName>
    </customValue>
    <customValue>
        <fullName>Rodos</fullName>
    </customValue>
    <customValue>
        <fullName>Pines</fullName>
    </customValue>
    <customValue>
        <fullName>Bujes</fullName>
    </customValue>
    <masterLabel>Subfamilia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unidad</fullName>
    </customValue>
    <customValue>
        <fullName>Par</fullName>
    </customValue>
    <customValue>
        <fullName>Caja 5 pies</fullName>
    </customValue>
    <customValue>
        <fullName>Caja 10 pies</fullName>
    </customValue>
    <customValue>
        <fullName>Juego</fullName>
    </customValue>
    <customValue>
        <fullName>Libra</fullName>
    </customValue>
    <masterLabel>Unidad de Medida</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClassQuote.cls
public with sharing class ClassQuote {
    @AuraEnabled
    public static Quote__c getQuote(String quoteId) {
        return [SELECT Name, Currency_Code__c, Discount__c, Total_In_Letters__c, Converted__c
                FROM Quote__c WHERE Id =: quoteId];
    }

    @AuraEnabled
    public static List<Quote_Line__c> getQuoteLines(String quoteId) {
        return [SELECT  Id,
                        Quote__c,
                        Product__c,
                        Index__c,
                        Description__c,
                        Time__c,
                        Quantity__c,
                        Type__c,
                        Time_In_Days__c,
                        Delivery_Time__c,
                        Brand__c,
                        Family__c,
                        Subfamily__c,
                        Unit__c,
                        Material__c,
                        Dimensions__c
                FROM Quote_Line__c
                WHERE Quote__c =: quoteId
                ORDER BY Index__c ASC];
    }

    @AuraEnabled
    public static List<Quote_Line__c> getProductsOfLines(String quoteId) {
        return [SELECT  Product__r.Id,
                        Product__r.Name,
                        Product__r.Old_Code__c,
                        Product__r.Description__c,
                        Product__r.Brand__c,
                        Product__r.Family__c,
                        Product__r.Subfamily__c,
                        Product__r.Unit__c,
                        Product__r.Material__c,
                        Product__r.Dimensions__c,
                        Product__r.Stock__c,
                        Product__r.Inventory_State__c,
                        Product__r.Price_GTQ__c,
                        Product__r.Price_USD__c
                FROM Quote_Line__c
                WHERE Quote__c =: quoteId
                ORDER BY Index__c ASC];
    }

    @AuraEnabled
    public static void saveQuote(Quote__c quote, List<Quote_Line__c> data) {
        String userId = UserInfo.getUserId();
        User user = [SELECT Discount_Max__c FROM User WHERE Id =: userId];

        if(user.Discount_Max__c < quote.Discount__c){
            throw new AuraHandledException('El descuento ingresado excede el rango que usted está autorizado.');
        }
        if(quote.Discount__c < 0){
            throw new AuraHandledException('El descuento ingresado no puede ser menor a 0.');
        }

        List<Quote_Line__c> linesToDelete = [
            SELECT Id
            FROM Quote_Line__c
            WHERE Id NOT IN : data AND Quote__c =: quote.Id];

        delete(linesToDelete);
        upsert(quote);
        upsert(data);
    }
}