force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Familia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Inventory_State__c.field-meta.xml
<CustomField>
    <fullName>Inventory_State__c</fullName>
    <formula>IF( Stock__c &lt; (Stock_Maximum__c -  Stock_Minimum__c) * 0.15 , &quot;Solicitar Material&quot;, 
 IF( Stock__c &lt; (Stock_Maximum__c -  Stock_Minimum__c) * 0.50 , &quot;Planificar Pedido&quot;, &quot;Inventario Suficiente&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estado en Inventario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Price_GTQ__c</fullName>
    <formula>Related_Price__r.Unit_Price_GTQ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price_USD__c.field-meta.xml
<CustomField>
    <fullName>Price_USD__c</fullName>
    <formula>Related_Price__r.Unit_Price_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Subfamily__c.field-meta.xml
<CustomField>
    <fullName>Subfamily__c</fullName>
    <label>Subfamilia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Subfamily</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unidad de Medida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subfamily__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Micro 100</fullName>
    </customValue>
    <customValue>
        <fullName>Fandher</fullName>
    </customValue>
    <customValue>
        <fullName>Flexitallic</fullName>
    </customValue>
    <customValue>
        <fullName>Workland</fullName>
    </customValue>
    <customValue>
        <fullName>General Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Kana</fullName>
    </customValue>
    <customValue>
        <fullName>Mausa</fullName>
    </customValue>
    <customValue>
        <fullName>Dedini</fullName>
    </customValue>
    <customValue>
        <fullName>Imbil</fullName>
    </customValue>
    <customValue>
        <fullName>Resonance</fullName>
    </customValue>
    <customValue>
        <fullName>Stanley</fullName>
    </customValue>
    <customValue>
        <fullName>Kestra</fullName>
    </customValue>
    <customValue>
        <fullName>Greenfield</fullName>
    </customValue>
    <customValue>
        <fullName>Cleveland</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago Latrobe</fullName>
    </customValue>
    <customValue>
        <fullName>Incor</fullName>
    </customValue>
    <customValue>
        <fullName>Genérico</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sellos Hidráulicos</fullName>
    </customValue>
    <customValue>
        <fullName>Cadena Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Herramienta de Corte</fullName>
    </customValue>
    <customValue>
        <fullName>Promocional</fullName>
    </customValue>
    <customValue>
        <fullName>Calzado Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Repuestos</fullName>
    </customValue>
    <customValue>
        <fullName>Soldadura</fullName>
    </customValue>
    <customValue>
        <fullName>Herramienta Manual</fullName>
    </customValue>
    <masterLabel>Familia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Subfamily.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Espirometálico tipo CG</fullName>
    </customValue>
    <customValue>
        <fullName>Espirometálico tipo CGI</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo RC</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Domo</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Oval</fullName>
    </customValue>
    <customValue>
        <fullName>Tipo Empaque</fullName>
    </customValue>
    <customValue>
        <fullName>Estopa</fullName>
    </customValue>
    <customValue>
        <fullName>Regalo para cliente</fullName>
    </customValue>
    <customValue>
        <fullName>Catálogo</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71820</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71821</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71822</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71823</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71824</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71825</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71826</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71827</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71828</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71829</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71830</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71831</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71832</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71833</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71834</fullName>
    </customValue>
    <customValue>
        <fullName>Modelo 71835</fullName>
    </customValue>
    <customValue>
        <fullName>Buril de Tungsteno</fullName>
    </customValue>
    <customValue>
        <fullName>Buril de Cobalto</fullName>
    </customValue>
    <customValue>
        <fullName>Rodos</fullName>
    </customValue>
    <customValue>
        <fullName>Pines</fullName>
    </customValue>
    <customValue>
        <fullName>Bujes</fullName>
    </customValue>
    <masterLabel>Subfamilia</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unidad</fullName>
    </customValue>
    <customValue>
        <fullName>Par</fullName>
    </customValue>
    <customValue>
        <fullName>Caja 5 pies</fullName>
    </customValue>
    <customValue>
        <fullName>Caja 10 pies</fullName>
    </customValue>
    <customValue>
        <fullName>Juego</fullName>
    </customValue>
    <customValue>
        <fullName>Libra</fullName>
    </customValue>
    <masterLabel>Unidad de Medida</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClassProduct.cls
public with sharing class ClassProduct {

    @AuraEnabled
    public static List<Product__c> getProducts(String input){
        String check = input.replace(' ', '');
        String searchValue = check.length() <= 0 ? '' : '%' + input + '%';

        return [
            SELECT  Id,
                    Name,
                    Description__c,
                    Brand__c,
                    Family__c,
                    Subfamily__c,
                    Unit__c,
                    Stock__c,
                    Inventory_State__c,
                    Price_GTQ__c,
                    Price_USD__c
            FROM Product__c
            WHERE Name LIKE : searchValue
            OR Description__c LIKE : searchValue];
    }
}