force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Related_Price__c.field-meta.xml
<CustomField>
    <fullName>Related_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Precio Relacionado</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El precio seleccionado no corresponde al producto.</errorMessage>
        <filterItems>
            <field>Product_Price__c.Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Precio de Producto</label>
    <nameField>
        <displayFormat>PRE-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Precios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Precios</relationshipLabel>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Margen de Ganancia</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Cost_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_GTQ__c</fullName>
    <label>Costo Unitario en Quetzales</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Unit_Price_GTQ__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price_GTQ__c</fullName>
    <label>Precio de Venta (Q)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestTrigger.cls
@IsTest
public class TestTrigger {
    @TestSetup
    static void createProducts(){
        TestSetup.createProducts();
    }

    private static List<Product_Price__c> generatePrices(){
        Product__c product = [SELECT Id, Stock__c FROM Product__c][0];
        List<Product_Price__c> prices = new List<Product_Price__c>();
        Product_Price__c price;

        price = new Product_Price__c();
        price.Quantity__c = 1;
        price.Unit_Cost_GTQ__c = 10;
        price.Profit__c = 100;
        price.Unit_Price_GTQ__c = 20;
        price.Product__c = product.Id;
        prices.add(price);

        price = new Product_Price__c();
        price.Quantity__c = 10;
        price.Unit_Cost_GTQ__c = 10;
        price.Profit__c = 100;
        price.Unit_Price_GTQ__c = 20;
        price.Product__c = product.Id;
        prices.add(price);

        price = new Product_Price__c();
        price.Quantity__c = 5;
        price.Unit_Cost_GTQ__c = 10;
        price.Profit__c = 100;
        price.Unit_Price_GTQ__c = 20;
        price.Product__c = product.Id;
        prices.add(price);

        insert prices;
        return prices;
    }

    @IsTest
    public static void updateProductStock() {
        Product__c product = [SELECT Id, Stock__c FROM Product__c][0];
        Decimal initialStock = product.Stock__c;

        Test.startTest();
        List<Product_Price__c> prices = generatePrices();
        product = [SELECT Id, Stock__c FROM Product__c][0];
        System.assertEquals(initialStock + 16, product.Stock__c, 'Incorrect stock retrieved');
        Test.stopTest();
    }

    @IsTest
    public static void deletePrices() {
        Product__c product = [SELECT Id, Related_Price__c FROM Product__c][0];
        List<Product_Price__c> generatedPrices = generatePrices();

        List<Product_Price__c> pricesToDelete = new List<Product_Price__c>();
        pricesToDelete.add(generatedPrices[2]);

        Test.startTest();
        ClassTrigger.deletePrices(pricesToDelete);
        product = [SELECT Id, Related_Price__c FROM Product__c][0];
        System.assertNotEquals(null, product.Related_Price__c, 'No related price was set to the product after deletion');
        Test.stopTest();
    }
}