force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Related_Price__c.field-meta.xml
<CustomField>
    <fullName>Related_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Precio Relacionado</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El precio seleccionado no corresponde al producto.</errorMessage>
        <filterItems>
            <field>Product_Price__c.Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Price__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/Product_Price__c.object-meta.xml
<CustomObject>
    <label>Precio de Producto</label>
    <nameField>
        <displayFormat>PRE-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Precios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Precios</relationshipLabel>
    <relationshipName>Product_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Price__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClassTrigger.cls
public with sharing class ClassTrigger {

    private static List<Product__c> getProductsToUpdate(List<Product_Price__c> prices){
        Set<String> productsIdSet = new Set<String>();
        for(Product_Price__c price : prices){
            productsIdSet.add(price.Product__c);
        }

        return !isQueryable() ? null : [
            SELECT Id, Stock__c, Related_Price__c,
                (SELECT Id, Quantity__c FROM Product_Prices__r ORDER BY Id DESC)
            FROM Product__c
            WHERE Id IN : productsIdSet
        ];
    }

    private static Boolean isQueryable (){
        return Schema.sObjectType.Product__c.isQueryable() && Schema.sObjectType.Product_Price__c.isQueryable();
    }

    public static void deletePrices(List<Product_Price__c> oldPrices){
        List<Product__c> products = getProductsToUpdate(oldPrices);
        for(Product__c product : products){
            product.Related_Price__c = product.Product_Prices__r[0].Id;
        }

        if ( Schema.sObjectType.Product__c.isUpdateable() ){
            update(products);
        }
    }


    public static void addProductStock(List<Product_Price__c> prices){
        List<Product__c> products = getProductsToUpdate(prices);

        Decimal stockToAdd;
        for(Product__c product : products){
            product.Related_Price__c = product.Product_Prices__r[0].Id;
            stockToAdd = 0;
            for(Product_Price__c price : product.Product_Prices__r){
                stockToAdd += price.Quantity__c;
            }

            product.Stock__c += stockToAdd;
        }

        if ( Schema.sObjectType.Product__c.isUpdateable() ){
            update(products);
        }
    }

    public static void updateProductStock(List<Product_Price__c> prices){
        for(Product_Price__c price : prices){
            price.addError('Los precios no pueden ser actualizados, intente crear uno nuevo.');
        }
    }
}