force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>PRO-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Linea de Cotización</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lineas de Cotización</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Cotización</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Lineas de Cotización</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestQuote.cls
@IsTest
public class TestQuote {
    @IsTest
    static void getQuote(){
        Quote__c quote = TestSetup.createQuote();
        Test.startTest();
        Quote__c actualQuote = ClassQuote.getQuote(quote.Id);
        System.assertEquals(quote.Id, actualQuote.Id, 'Quote retrieve is not the same as expected');
        Test.stopTest();
    }

    @IsTest
    static void getQuoteLines(){
        Quote__c quote = TestSetup.createQuote();
        Test.startTest();
        List<Quote_Line__c> quoteLines = ClassQuote.getQuoteLines(quote.Id);
        System.assertEquals(3, quoteLines.size(), 'Quote lines retrieve are not the same as expected');
        Test.stopTest();
    }

    @IsTest
    static void getProductsOfLines(){
        Quote__c quote = TestSetup.createQuote();
        Test.startTest();
        List<Quote_Line__c> linesWithProducts = ClassQuote.getProductsOfLines(quote.Id);
        System.assertEquals(3, linesWithProducts.size(), 'Quote lines retrieve are not the same as expected');
        System.assertEquals('Sierras', linesWithProducts[1].Product__r.Description__c, 'Product is not the same as expected');
        Test.stopTest();
    }

    @IsTest
    static void saveQuote(){
        Quote__c quote = TestSetup.createQuote();
        List<Quote_Line__c> quoteLines = [SELECT Id FROM Quote_Line__c WHERE Quote__c =: quote.Id LIMIT 2];
        Test.startTest();
        ClassQuote.saveQuote(quote, quoteLines);
        quoteLines = [SELECT Id FROM Quote_Line__c WHERE Quote__c =: quote.Id];
        System.assertEquals(2, quoteLines.size(), 'Quote lines retrieve are not the same as expected');

        String negativeDiscountException = null;
        try {
            quote.Discount__c = -5;
            ClassQuote.saveQuote(quote, quoteLines);
        } catch (Exception e){
            negativeDiscountException = e.getMessage();
        }
        System.assertNotEquals(null, negativeDiscountException, 'Saving negative discount has to throw an exception.');

        String discountException = null;
        try {
            quote.Discount__c = 1000;
            ClassQuote.saveQuote(quote, quoteLines);
        } catch (Exception e){
            discountException = e.getMessage();
        }
        System.assertNotEquals(null, discountException, 'Saving grater discounts has to throw an exception.');

        Test.stopTest();
    }
}